#!/usr/bin/env bash

add_info() {
  local concept=$1
  local definition=$2
  local method=$3
  local dir=$4

  echo "[$concept] .- $definition " >> "$dir"/"$method".inf &&\
  echo "Entry added:" && echo &&\
  echo "Method: $method" &&\
  echo "Concept: $concept" &&\
  echo "Definition: $definition"
}
