#!/usr/bin/env bash

bootstrap() {
  script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
  dir="$script_dir"/methods
  [[ ! -d "$dir" ]] && mkdir -p "$dir"

  files=("$dir/scrum.inf" "$dir/xp.inf" "$dir/kanban.inf" "$dir/kanban.inf" "$dir/crystal.inf" "$dir/cascade.inf" "$dir/spiral.inf" "$dir/v_model.inf")
  create=()
  for file in "${files[@]}"; do
    [[ ! -f "$file" ]] && create+=("$file")
  done

  [[ ${#create[@]} -eq 0 ]] && return

  echo "The following files were created for the execution of the program:"
  for file in "${create[@]}"; do
    [[ ! -f "$file" ]] && touch "$file" && echo "- Created: $file"
  done
  echo -e "\nTo continue please Press ENTER"
  read
}
