#!/usr/bin/env bash

source parse_line

content_info() {
  local method=$1
  local dir=$2
  local file="$dir"/"$method".inf

  while IFS= read -r line; do
    parse_line "$line"
    echo "Concept:   $concept"
    echo "Definition $definition"; echo
  done < "$file"
}
