#!/usr/bin/env bash

source parse_line
source search_info

delete_info() {
  local pattern=$1
  local method=$2
  local dir=$3
  local file="$dir"/"$method".inf

  result=$(search_info "$pattern" "$method" "$dir")
  [[ "$result" == "No resulting matches" ]] && echo "No resulting matches" && return

  sed -i "/\[$pattern\] .- /d" "$file"
  echo "$pattern deleted"
}
