#!/usr/bin/env bash

source parse_line

function search_info {
  local pattern=$1
  local method=$2
  local dir=$3
  local file="$dir"/"$method".inf

  matches=$(grep -E "\[$pattern\]" "$file") # format: [concept]

  if [[ -z "$matches" ]]; then
    echo "No resulting matches"
    return
  fi

  echo "Matches found:"
  echo

  while IFS= read -r line; do
    parse_line "$line"
    echo "   $concept"
    echo "   $definition"; echo
  done <<< "$matches"
}
